# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system_app', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='profile_img',
        ),
    ]
